### ISSUE TITLE
Missing EventSystem

### ISSUE THREAD

**Issue by GabrielCapeletti** [loicteixeira/gj-unity-api#45]
Adding the GamerJoltAPI object in my scene and then calling GameJolt.UI.Manager.Instance.ShowSignIn();
is generating an error : NullReferenceException: Object reference not set to an instance of an object
UnityEngine.UI.Selectable.Select ().
I added a new EventSystem to the scene and it worked fine.
The EventSystem should come with the API object.
I guess someone just deleted it by mistake.

**Comment by loicteixeira** [comment]
Thanks for your feedback Gabriel.

- Which version of the API do you have installed? It should be fixed in 2.0.1
- Did you imported the prefab manually by dragging it from the project window? The prefab should always be instantiated from the GameObject menu. Indeed, from 2.0.1, it will instantiate the EventSystem if there is none.

**Comment by GabrielCapeletti** [comment]
Used the 2.0.0 version. 
Yes I followed the tutorial going on GameObject tab -> GameJoldManager.
I was using unity 5.

**Comment by loicteixeira** [comment]
Alright. As I said that behaviour should be fixed in version 2.0.1 (it will create an EventSystem if there isn't one already). Closing the ticket for now. Please reopen it if it is still happening with 2.0.1
