### ISSUE TITLE
Change license to less restrictive

### ISSUE THREAD

**Issue by r2d2rigo** [loicteixeira/gj-unity-api#62]
Hello, I have noticed that the license for this project is GPLv2. This means that **any** game that includes this library must be released under GPLv2 too:

>   5. You are not required to accept this License, since you have not
> signed it.  However, nothing else grants you permission to modify or
> distribute the Program or its derivative works.  These actions are
> prohibited by law if you do not accept this License.  Therefore, by
> modifying or distributing the Program (or any work based on the
> Program), you indicate your acceptance of this License to do so, and
> all its terms and conditions for copying, distributing or modifying
> the Program or works based on it.

I know GameJolt doesn't have paid games for now, but even so, many of the ones published in there aren't open sourced; using your library and not opensourcing them would make them violate the license.

Please reconsider changing it to LGPL or MIT/BSD.

**Comment by loicteixeira** [comment]
Thanks for your input. Another member on the forum raised the same issue and [adviced to use LGPL or MIT](http://gamejolt.com/x/permalink/forum-post/65014) as well. I shouldn't have left this running for so long.

I initially thought that it was a bad thing to change a license type because you change what people agreed on basically. But to be honest, I don't think anybody really read the license, and as far as my understanding goes, LGPL and MIT are less restrictive than GPLv2.
